
-- 시퀀스추가
CREATE SEQUENCE SQ_LCMS_TOC_SEQ
 	 START WITH 1
 	 MAXVALUE 9223372036854775807
 	 MINVALUE 0
 	 NOCYCLE 
 	 CACHE 10
 	 NOORDER 

;
CREATE SEQUENCE SEQ_LCMS_METADATA_SEQ
 	 START WITH 1
 	 MAXVALUE 9999999999
 	 MINVALUE 1
 	 NOCYCLE 
 	 CACHE 10
 	 NOORDER 

;








INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/title', 'string', '타이틀', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/title', 'string', '타이틀', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/title', 'string', '타이틀', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/keyword', 'string', '키워드', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/keyword', 'string', '키워드', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/keyword', 'string', '키워드', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/keyword', 'string', '키워드', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/description', 'string', '설명', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/description', 'string', '설명', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/description', 'string', '설명', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/description', 'string', '설명', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/technical', 'format', '강의유형', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/technical', 'format', '강의유형', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/technical', 'format', '강의유형', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/technical', 'format', '강의유형', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/difficulty', 'value', '난이도', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/difficulty', 'value', '난이도', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/difficulty', 'value', '난이도', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/difficulty', 'value', '난이도', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/description', 'string', '총학습분량', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/description', 'string', '총학습분량', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/description', 'string', '총학습분량', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/description', 'string', '총학습분량', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general', 'language', '언어', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/title', 'string', '타이틀', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general', 'language', '언어', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general', 'language', '언어', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general', 'language', '언어', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/version', 'string', '버전', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/version', 'string', '버전', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/version', 'string', '버전', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/version', 'string', '버전', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/status', 'value', '버전상태', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/status', 'value', '버전상태', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/status', 'value', '버전상태', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/status', 'value', '버전상태', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/role', 'value', '담당교수', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/role', 'value', '담당교수', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/role', 'value', '담당교수', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/role', 'value', '담당교수', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute', 'entity', '개발업체명', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute', 'entity', '개발업체명', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute', 'entity', '개발업체명', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute', 'entity', '개발업체명', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/date', 'dateTime', '제작날짜', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/date', 'dateTime', '제작날짜', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/date', 'dateTime', '제작날짜', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/date', 'dateTime', '제작날짜', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/rights/cost', 'value', '유료/무료', 'Y', 'LOM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/rights/cost', 'value', '유료/무료', 'Y', 'LOM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/rights/cost', 'value', '유료/무료', 'Y', 'LOM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/rights/cost', 'value', '유료/무료', 'Y', 'LOM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/title', 'string', '타이틀', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/keyword', 'string', '키워드', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general/description', 'string', '설명', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/technical', 'format', '강의유형', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/difficulty', 'value', '난이도', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/educational/description', 'string', '총학습분량', 'Y', 'LOM', 'TEMPLATE'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/general', 'language', '언어', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/version', 'string', '버전', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/status', 'value', '버전상태', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/role', 'value', '담당교수', 'Y', 'LOM', 'TEMPLATE'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute', 'entity', '개발업체명', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/lifeCycle/contribute/date', 'dateTime', '제작날짜', 'Y', 'LOM', 'TEMPLATE'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'lom/rights/cost', 'value', '유료/무료', 'Y', 'LOM', 'TEMPLATE', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/title', 'string', '제목', 'Y', 'KEM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/title', 'string', '제목', 'Y', 'KEM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/title', 'string', '제목', 'Y', 'KEM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/title', 'string', '제목', 'Y', 'KEM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/subTitle', 'string', '부제', 'Y', 'KEM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/subTitle', 'string', '부제', 'Y', 'KEM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/subTitle', 'string', '부제', 'Y', 'KEM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/subTitle', 'string', '부제', 'Y', 'KEM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/tableOfContents', 'string', '목차', 'Y', 'KEM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/tableOfContents', 'string', '목차', 'Y', 'KEM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/tableOfContents', 'string', '목차', 'Y', 'KEM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/general/tableOfContents', 'string', '목차', 'Y', 'KEM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/teachingMethod', 'string', '교수방법', 'Y', 'KEM', 'COA'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/teachingMethod', 'string', '교수방법', 'Y', 'KEM', 'SCO'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/teachingMethod', 'string', '교수방법', 'Y', 'KEM', 'ITM'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/teachingMethod', 'string', '교수방법', 'Y', 'KEM', 'ORG'
, 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/environment', 'string', '환경', 'Y', 'KEM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/environment', 'string', '환경', 'Y', 'KEM', 'ORG', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/environment', 'string', '환경', 'Y', 'KEM', 'ITM', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/environment', 'string', '환경', 'Y', 'KEM', 'SCO', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/assessment', 'string', '평가', 'Y', 'KEM', 'COA', 1); 
INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/assessment', 'string', '평가', 'Y', 'KEM', 'ORG', 1); 

INSERT INTO TB_LCMS_METADATA_MAP ( SEARCH_YN, ELEMENT_PATH, ELEMENT_NAME, ELEMENT_TITLE, READONLY,
METATYPE, OBJ_TYPE, PRE_GROUP ) VALUES ( 
'N', 'kem/educational/pedagogy/assessment', 'string', '평가', 'Y', 'KEM', 'ITM', 1); 
commit;
 
