var messageString = new JMap(); 

messageString.put('LE_message_001', '신청시작일자가 종료일자보다 클 수 없습니다.'); 
messageString.put('LE_message_002', '신청종료일자가 현재일자보다 작을 수 없습니다.'); 
messageString.put('LE_message_003', '교육기간보다 신청기간이 클 수 없습니다.'); 
messageString.put('LE_message_004', '이미 수료 처리된 수강생이 존재합니다.'); 
messageString.put('LE_message_005', '이미 미수료 처리된 수강생이 존재합니다.'); 
messageString.put('LE_message_006', '학습 전 입니다.'); 
messageString.put('LE_message_007', '학습이 완료 되었습니다.'); 
messageString.put('LE_message_008', '이미 승인된 수강생이 존재합니다.'); 
messageString.put('LE_message_009', '이미 미승인된 수강생이 존재합니다.'); 
messageString.put('LE_message_010', '시스템그룹인 경우 삭제할 수 없습니다.'); 
messageString.put('LE_message_011', '그룹에 회원이 존재하는 경우 삭제할 수 없습니다.'); 
messageString.put('LE_message_012', '기간은 교육기간 범위 내에서 입력하십시오.'); 
messageString.put('LE_message_013', '과제점수 가중치값을 정확하게 입력하십시오.'); 
messageString.put('LE_message_014', '1 ~ 100 범위안의 숫자를 입력하세요.'); 
messageString.put('LE_message_015', '수강인원은 1명  이상이어야 합니다.'); 
messageString.put('LE_message_016', '자동수료처리 하시겠습니까?'); 
messageString.put('LE_message_017', '교육완료된 강좌는 삭제할 수 없습니다.'); 
messageString.put('LE_message_018', '선택하신 강좌는 하위정보가 존재하여 삭제할 수 없습니다.'); 
messageString.put('LE_message_019', '해당 차시의 점수정보가 존재합니다. 차시 삭제 시 점수정보도 함께 삭제됩니다. 삭제 하시겠습니까?'); 
messageString.put('LE_message_020', '종료 시간이 시작 시간보다 커야 합니다.'); 
messageString.put('LE_message_021', '수정할 권한이 없습니다.'); 
messageString.put('LE_message_022', '삭제할 수 없는 공통코드입니다.'); 
messageString.put('LE_message_023', '하위 데이터가 존재하므로 삭제할수 없습니다.'); 
messageString.put('LS_message_001', '[ 실험장비예약 ] 및 [ 센서예약 ]에 예약한 내용이 있으면 모두 삭제됩니다.삭제하시겠습니까?'); 
messageString.put('LS_message_002', '예약한 시간을 수정할 경우, 기존에 입력한 [실험장비예약] 및 [센서예약] 정보가 초기화됩니다.실험예약시간을 수정하시겠습니까?'); 
messageString.put('LS_message_003', '보정이력도 삭제됩니다.삭제하시겠습니까?'); 
messageString.put('LS_message_004', '하위장비의 실험실명이 현재의 실험실명으로 변경됩니다.'); 
messageString.put('LS_message_005', '예약 하시겠습니까?'); 
messageString.put('LS_message_006', '예약취소 하시겠습니까? '); 
messageString.put('LS_message_007', '실험을 확정하시겠습니까? '); 
messageString.put('LS_message_008', '실험확정을 취소하시겠습니까? '); 
messageString.put('LS_message_009', '해당 실험장비를 태스크사용장비 목록에 등록하시겠습니까?'); 
messageString.put('LS_message_010', '해당 실험장비를 태스크사용장비 목록에서 삭제하시겠습니까?'); 
messageString.put('LS_message_011', '공개데이터형식을 변경시 이전데이터는 모두 삭제 됩니다. 계속하시겠습니까?'); 
messageString.put('LS_message_012', '해당 센서를 태스크사용센서 목록에 등록하시겠습니까?'); 
messageString.put('LS_message_013', '해당 센서를 태스크사용센서 목록에서 삭제하시겠습니까?'); 
messageString.put('LS_message_014', '등록완료하시겠습니까?'); 
messageString.put('LS_message_015', '등록취소하시겠습니까?'); 
messageString.put('LS_message_016', '실험승인하시겠습니까?'); 
messageString.put('LS_message_017', '승인취소 시 [ 프로젝트 참여자 ], [ 프로젝트 실험비용 ] 정보가 모두 삭제됩니다.승인취소하시겠습니까?'); 
messageString.put('LS_message_018', '선택하신 예비계획을 복사하시겠습니까?'); 
messageString.put('LS_message_101', '센서예약 수량을 입력하십시오.'); 
messageString.put('LS_message_201', '[ 실험센터일정예약 ]에 입력된 정보가 있어서 삭제할 수 없습니다.확인하시기 바랍니다.'); 
messageString.put('LS_message_202', '[ 실험시간예약 ]에 입력된 정보가 있어서 삭제할 수 없습니다.확인하시기 바랍니다.'); 
messageString.put('LS_message_203', '종료 시간이 시작 시간보다 커야 합니다.입력한 시간을 확인하시기 바랍니다.'); 
messageString.put('LS_message_204', '센서모델에 속한 센서가 존재하므로 삭제할 수 없습니다.'); 
messageString.put('LS_message_205', '실험실에 속한 장비가 존재하므로 삭제할 수 없습니다.'); 
messageString.put('LS_message_206', '폐기일이 도입일보다 먼저일 수 없습니다.'); 
messageString.put('LS_message_207', '하위장비가 존재하므로 하위장비로 변경할수 없습니다.'); 
messageString.put('LS_message_208', '실험실명을 선택하세요.'); 
messageString.put('LS_message_209', '범위순서가 잘못되었습니다.'); 
messageString.put('LS_message_210', '센서예약수량이 예약가능수량보다 클 수 없습니다.'); 
messageString.put('LS_message_211', '공개여부가 \'예\'인 공개데이터는 삭제할 수 없습니다.'); 
messageString.put('LS_message_212', '공개데이터에 첨부된 파일이 존재하므로 삭제할 수 없습니다.'); 
messageString.put('LS_message_213', '태스크의 등록된 정보가 있어서 삭제할 수 없습니다.'); 
messageString.put('LS_message_214', '모델의 등록된 정보가 있어서 삭제할 수 없습니다.'); 
messageString.put('LS_message_215', 'Trial의 등록된 정보가 있어서 삭제할 수 없습니다.'); 
messageString.put('LS_message_216', '프로젝트에 속한 데이타가 존재하므로 승인취소를 할 수 없습니다.'); 
messageString.put('LS_message_217', '실험센터일정이 등록되지 않았습니다. 리스트에서 실험센터일정을 등록해 주십시오.'); 
messageString.put('LS_message_218', '문제가 발생하여 예비계획 복사를 실패하였습니다.관리자에게 문의하시기 바랍니다.'); 
messageString.put('LS_message_219', '공개일이 등록일보다 먼저일 수 없습니다.'); 
messageString.put('LS_message_220', '비공개 프로젝트인 경우 1개의 실험센터만 예약가능합니다.'); 
messageString.put('LS_message_221', '로그인 후 사용하십시오.'); 
messageString.put('message_001', '선택된 정보를 삭제하시겠습니까?'); 
messageString.put('message_002', '변경된 정보를 저장하시겠습니까?'); 
messageString.put('message_003', '이미 자료가 존재합니다. 삭제하시겠읍니까?'); 
messageString.put('message_004', '작업이 완료되었습니다. 저장하시겠습니까?'); 
messageString.put('message_005', '작업을 취소하시겠습니까?'); 
messageString.put('message_006', '해당되는 코드가 없습니다. 신규등록 하시겠습니까?'); 
messageString.put('message_007', '등록된 사진이 없읍니다. 신규등록하시겠습니까?'); 
messageString.put('message_008', '기존의 자료는 보관하고 새로운 자료를 등록하시겠읍니까?'); 
messageString.put('message_009', '삭제하시겠습니까?'); 
messageString.put('message_010', '저장하시겠습니까?'); 
messageString.put('message_011', '결재요청을 하시겠습니까?'); 
messageString.put('message_012', '요청취소 하시겠습니까?'); 
messageString.put('message_013', '등록하시겠습니까?'); 
messageString.put('message_014', '탈퇴처리 하시겠습니까?'); 
messageString.put('message_015', '휴면처리 하시겠습니까?'); 
messageString.put('message_016', '파일을 삭제하시겠습니까?'); 
messageString.put('message_017', '과제확인 승인을 하시겠습니까?'); 
messageString.put('message_018', '기수를 삭제하시겠습니까?'); 
messageString.put('message_019', '선택된 수강생을 수강승인 처리하시겠습니까?'); 
messageString.put('message_020', '선택된 수강생을 수강미승인 처리하시겠습니까?'); 
messageString.put('message_021', '수강승인 처리하시겠습니까?'); 
messageString.put('message_022', '수강미승인 처리하시겠습니까?'); 
messageString.put('message_023', '가입  처리하시겠습니까?'); 
messageString.put('message_024', '선택된 그룹으로 변경하시겠습니까?'); 
messageString.put('message_025', '영재회원 신청을 하시겠습니까?'); 
messageString.put('message_026', '강원에듀원 회원가입을 신청하시겠습니까?'); 
messageString.put('message_027', '강원에듀원 회원으로 전환하시겠습니까? 확인을 누르시면 강원에듀원 회원으로 등록됩니다.'); 
messageString.put('message_028', '장애신고 신청을 하시겠습니까?'); 
messageString.put('message_029', '수료증 출력 횟수는 1회로 제한되어 있으니 프린터상태등을 확인하여 주시기 바랍니다. 출력 하시겠습니까?'); 
messageString.put('message_030', '초기화된 데이터는 복구할 수 없습니다.데이터 백업 후 초기화를 진행하여 주시기 바랍니다.초기화 하시겠습니까?'); 
messageString.put('message_101', '조회 내용이 없습니다.'); 
messageString.put('message_102', '처리가 완료되었습니다.'); 
messageString.put('message_103', '변경된 내용이 없습니다.'); 
messageString.put('message_104', '해당되는 정보가 존재하지 않습니다.'); 
messageString.put('message_105', '정상적으로 저장되었습니다.'); 
messageString.put('message_106', '정상적으로 수정되었습니다.'); 
messageString.put('message_107', '정상적으로 삭제되었습니다.'); 
messageString.put('message_108', '성공적으로 복사되었습니다.'); 
messageString.put('message_109', '조회년도를 확인하세요.'); 
messageString.put('message_110', '필수입력 항목 입니다.'); 
messageString.put('message_111', '학번을 다시 입력하세요.'); 
messageString.put('message_112', '패스워드 오류가 발생하였습니다.'); 
messageString.put('message_113', '작업이 취소되었습니다.'); 
messageString.put('message_114', '년도와 학기를 선택하십시오.'); 
messageString.put('message_115', '정정처리를 다시 하시기 바랍니다.'); 
messageString.put('message_116', '기간을 확인하세요.'); 
messageString.put('message_117', '조건에 해당하는 대상인원이 존재하지 않습니다.'); 
messageString.put('message_118', '주,야간반을 선택하십시오.'); 
messageString.put('message_119', '건물코드를 확인하세요.'); 
messageString.put('message_120', '주야구분이 잘못되었습니다. 주야구분을 확인하세요.'); 
messageString.put('message_121', '학기를 먼저 입력하세요.'); 
messageString.put('message_122', '교과목코드를 먼저 입력하세요.'); 
messageString.put('message_123', '저장을 먼저 하신 후 작업하십시오.'); 
messageString.put('message_124', '복사할 자료가 존재하지 않습니다.'); 
messageString.put('message_125', '세부 항목을 입력하세요.'); 
messageString.put('message_126', '이미 입력된 학생입니다.'); 
messageString.put('message_127', '입력한 기간이 기존의 정보 수정기간과 중복됩니다.'); 
messageString.put('message_128', '월을 정확히 입력하셔야 합니다.'); 
messageString.put('message_129', '작업할 자료가 존재하지 않습니다.'); 
messageString.put('message_130', '자료가 하나도 없거나 읽어올 수가 없습니다.'); 
messageString.put('message_131', '정확한 값이 아닙니다.'); 
messageString.put('message_132', '입력범위 초과입니다.'); 
messageString.put('message_133', '삭제할 데이터가 없습니다.'); 
messageString.put('message_134', '처리할 자료가 없습니다.'); 
messageString.put('message_135', '해당 학부가 존재하지 않습니다.'); 
messageString.put('message_137', 'Y/N만 입력 가능합니다.'); 
messageString.put('message_138', '처리된 건수가 없습니다.'); 
messageString.put('message_139', '학적에 존재하지 않는 학생이거나 등록대상자로 선정되어 있지 않은 학생입니다.'); 
messageString.put('message_140', '처리 대상을 입력하십시요.'); 
messageString.put('message_141', '해당 학생이 존재하지 않습니다.'); 
messageString.put('message_142', '데이터가 없습니다.'); 
messageString.put('message_143', '자료가 없습니다.'); 
messageString.put('message_144', '삭제할 권한이 없습니다.'); 
messageString.put('message_145', '입력, 수정할 권한이 없습니다.'); 
messageString.put('message_146', '종료일자가 시작일자보다 작을 수 없습니다.'); 
messageString.put('message_147', '삭제되었습니다.'); 
messageString.put('message_148', '이전 자료가 없습니다.'); 
messageString.put('message_149', '자료를 읽어올수 없읍니다.'); 
messageString.put('message_150', '자료를 정확하게 입력하십시요.'); 
messageString.put('message_151', '저장이 완료되었읍니다.'); 
messageString.put('message_152', '작업대상이 선택되지 않았습니다.'); 
messageString.put('message_153', '학기를 확인하십시요.'); 
messageString.put('message_154', '전공부서를 확인하십시요.'); 
messageString.put('message_155', '관리부서를 확인하십시요.'); 
messageString.put('message_156', '관리부서를 선택하십시요.'); 
messageString.put('message_157', '우편번호가 존재하지 않습니다.'); 
messageString.put('message_158', '부서권한을 확인하세요.'); 
messageString.put('message_159', '작업을 취소하였습니다.'); 
messageString.put('message_160', '사업자등록번호가 유효하지 않습니다.'); 
messageString.put('message_161', '이미 해당 데이타가 존재합니다. 다시 입력하세요.'); 
messageString.put('message_162', '이미 해당 데이타의 상위코드가 존재합니다. 다시 입력하세요.'); 
messageString.put('message_163', '수정할 자료가 존재하지 않습니다.'); 
messageString.put('message_164', '동일한 사업자등록번호가 존재합니다.'); 
messageString.put('message_165', '해당 단위시스템에 권한이 없습니다.'); 
messageString.put('message_166', '병무청코드가 변경되었습니다.'); 
messageString.put('message_167', '종료일이 시작일보다 적습니다. 다시 입력하세요.'); 
messageString.put('message_168', '건 처리.'); 
messageString.put('message_169', '건 오류.'); 
messageString.put('message_170', '정수이외의 값은 허용하지 않습니다. 다시 입력하세요.'); 
messageString.put('message_171', 'ID/PW에 대한 내역이 메일로 발송되었습니다.'); 
messageString.put('message_172', 'ID/PW가 맞지 않은 경우 하루에 로그인 10 회이상를 할 수 없습니다.'); 
messageString.put('message_173', '건 저장하였습니다.'); 
messageString.put('message_174', '건 수정하였습니다.'); 
messageString.put('message_175', '건 삭제하였습니다.'); 
messageString.put('message_176', '건 복사하였습니다.'); 
messageString.put('message_177', '결재요청을 하였습니다.'); 
messageString.put('message_178', '결재요청을 취소하였습니다.'); 
messageString.put('message_179', '년도를 선택하세요.'); 
messageString.put('message_180', '약관 동의를 확인해 주세요.'); 
messageString.put('message_181', '하위 데이터가 존재하지 않아서 순서 이동을 할 수 없습니다.'); 
messageString.put('message_182', '값을 입력해 주세요.'); 
messageString.put('message_183', '중복확인을 하세요.'); 
messageString.put('message_184', '정상적으로 수강신청 되었습니다.'); 
messageString.put('message_185', '선택하세요.'); 
messageString.put('message_186', '정보가 변경되었습니다.'); 
messageString.put('message_187', '사용가능한 수료증 번호입니다.'); 
messageString.put('message_188', '로그인 되어 있지 않습니다. 로그인 페이지로 이동합니다.'); 
messageString.put('message_189', '온라인 차시가 선택되지 않았습니다. 선택해 주십시요.'); 
messageString.put('message_190', '선택하신 구분에 해당하는 검색어를 입력해 주십시요.'); 
messageString.put('message_191', '이미 사용하고 계신 계정이 있습니다.'); 
messageString.put('message_192', '현재 시범운영기간이며 준비중인 서비스 입니다.'); 
messageString.put('message_193', '입력하신 정보와 일치하는 계정이 존재합니다.아이디/비번 찾기를 이용하십시오.'); 
messageString.put('message_194', '장애신고가 정상적으로 접수되었습니다.'); 
messageString.put('message_195', '개인정보 보호정책에 동의해 주세요.'); 
messageString.put('message_196', '수료증 출력횟수는 1회로 제한되어 있습니다.이전 수료증출력 정보가 존재합니다.'); 
messageString.put('message_201', '기존자료는 삭제할 수 없습니다.'); 
messageString.put('message_202', '등록되지 않은 코드입니다.'); 
messageString.put('message_203', '자료가 이미 등록되어 있습니다.'); 
messageString.put('message_204', '데이타베이스 엑세스에러가 발생하였습니다.'); 
messageString.put('message_205', '입력오류입니다.'); 
messageString.put('message_206', '자료조회중 오류가 발생하였습니다.'); 
messageString.put('message_207', '입력할 수 없는 코드 길이 입니다.'); 
messageString.put('message_208', '시작일이 종료일 보다 크게 입력될 수 없습니다.'); 
messageString.put('message_209', '정의되지 않은 오류입니다.'); 
messageString.put('message_210', '존재하지 않는 사용자입니다.'); 
messageString.put('message_211', '존재하지 않는 업무그룹입니다.'); 
messageString.put('message_212', '권한이 없습니다.'); 
messageString.put('message_213', '선택한 자료가 없습니다.'); 
messageString.put('message_214', '자료 저장중 에러가 발생하였습니다.'); 
messageString.put('message_215', '해당되는 에러코드가 존재하지 않습니다.'); 
messageString.put('message_216', '검색조건이 지정되어 있지 않습니다.'); 
messageString.put('message_217', '등록되지 않은 프로그램입니다.'); 
messageString.put('message_218', '데이터베이스에 연결할 수 없습니다. 담당자에게 문의하세요.'); 
messageString.put('message_219', '데이터베이스가 존재하지 않습니다.'); 
messageString.put('message_220', '2대의 입력화면을 동시에 사용할 수 없습니다.'); 
messageString.put('message_221', '자료를 삭제할 수 없습니다.'); 
messageString.put('message_222', '이미 5개 이상의 화면이 사용중입니다.'); 
messageString.put('message_223', '자료 중복입니다.'); 
messageString.put('message_224', '처리중 오류가 발생하였습니다.'); 
messageString.put('message_225', '시작값이 종료값보다 클 수 없습니다.'); 
messageString.put('message_226', '조회할 권한이 없습니다.'); 
messageString.put('message_227', '종료일이 시작일보다 커야 합니다.'); 
messageString.put('message_228', '시간이 0보다 작을 수 없습니다.'); 
messageString.put('message_229', '시작, 종료값을 확인하세요.'); 
messageString.put('message_230', '입력할 수 있는 상한기준을 넘었습니다.'); 
messageString.put('message_231', '해당월의 한도(1~12)를 초과하였습니다.'); 
messageString.put('message_232', '요일을 입력하세요.'); 
messageString.put('message_233', '해당되는 메세지가 등록되어 있지 않습니다.'); 
messageString.put('message_234', '해당 계열구분이 존재하지 않습니다.'); 
messageString.put('message_235', '이미 해당자료가 존재합니다.'); 
messageString.put('message_236', '필수입력 항목입니다.'); 
messageString.put('message_237', '해당코드번호가 이미 존재합니다.'); 
messageString.put('message_238', '해당코드가 존재하지 않습니다.'); 
messageString.put('message_239', '해당 학과가 관리코드에 존재하지 않습니다.'); 
messageString.put('message_240', '총건수 확인중 오류가 발생하였습니다.'); 
messageString.put('message_241', '해당하는 정보가 존재하지 않습니다.'); 
messageString.put('message_242', '삭제시 오류가 발생했습니다.'); 
messageString.put('message_243', '자료 생성 중 오류가 발생했습니다.'); 
messageString.put('message_244', '자료저장시 오류가 발생하였습니다.'); 
messageString.put('message_245', '입력할 수 없습니다.'); 
messageString.put('message_246', '선택할 수 없는 항목입니다.'); 
messageString.put('message_247', '선택된 파일이 없습니다.'); 
messageString.put('message_248', '삭제된 건수가 다릅니다. 확인 바랍니다.'); 
messageString.put('message_249', '새롭게 생성할 자료가 없읍니다.'); 
messageString.put('message_250', '파일 저장시 오류가 발생하였읍니다.'); 
messageString.put('message_251', '아이디가 존재하지 않습니다. 다시 입력하세요.'); 
messageString.put('message_252', '비밀번호가 맞지않습니다. 다시 입력하세요.'); 
messageString.put('message_253', '이미 동일한 아이디로 접속한 사용자가 있습니다.'); 
messageString.put('message_254', '동일한 사용자ID가 존재합니다. 다시 입력하세요.'); 
messageString.put('message_255', '동일한 교직원번호가 존재합니다. 다시 입력하세요.'); 
messageString.put('message_256', '관리자에게 문의 하세요 (Worker Error).'); 
messageString.put('message_257', 'JPG, GIF, PNG 파일만 등록 가능합니다.'); 
messageString.put('message_258', '월 입력 오류입니다.'); 
messageString.put('message_259', '일 입력 오류입니다.'); 
messageString.put('message_260', '입학년도 또는 졸업년도 입력 오류입니다.'); 
messageString.put('message_261', '잘못된 주민등록 번호입니다.'); 
messageString.put('message_262', '종료일자가 시작일자보다 작을 수 없습니다.'); 
messageString.put('message_263', '시작일자와 종료일자를 확인하십시요.'); 
messageString.put('message_264', '삭제될 내용이 선택되지 않았습니다.'); 
messageString.put('message_265', '시스템을 사용할 권한이 없습니다.'); 
messageString.put('message_266', '데이터를 변경/삭제할 수 없습니다.'); 
messageString.put('message_267', '데이터를 저장할 수 없습니다.'); 
messageString.put('message_268', '데이터가 존재하므로 삭제할수 없습니다.'); 
messageString.put('message_269', '개인별 프로그램관리에 데이터가 존재하므로 삭제할수 없습니다.'); 
messageString.put('message_270', '업무그룹별 프로그램관리에 데이터가 존재하므로 삭제할수 없습니다.'); 
messageString.put('message_271', '사용시간이 만료되었습니다.\n 초기화면으로 이동합니다.'); 
messageString.put('message_272', '초기 화면으로 이동합니다.'); 
messageString.put('message_273', '프로그램을 사용할 권한이 없습니다.'); 
messageString.put('message_274', '세션이 종료되었습니다.'); 
messageString.put('message_275', '시스템코드 값이 없습니다.'); 
messageString.put('message_276', '시스템명 값이 없습니다.'); 
messageString.put('message_277', '과정분류명  값이 없습니다.'); 
messageString.put('message_278', '수정할 시스템명  값이 없습니다.'); 
messageString.put('message_279', '수정할 과정분류명  값이 없습니다.'); 
messageString.put('message_280', '하위 분류가 있습니다.하위 분류를 먼저 삭제 하시기 바랍니다.'); 
messageString.put('message_281', '순서 변경할 하위분류가 최소 2개 이상  존재하여야 합니다.'); 
messageString.put('message_282', '항목을 선택(입력) 하십시오.'); 
messageString.put('message_283', '항목 내용을 확인하십시오.'); 
messageString.put('message_284', '제한된 글자수를 넘었습니다.'); 
messageString.put('message_285', '추가 할 항목이 선택되지 않았습니다.'); 
messageString.put('message_286', '삭제 할 항목이 선택되지 않았습니다.'); 
messageString.put('message_287', '수정 할 항목이 선택되지 않았습니다.'); 
messageString.put('message_288', '그룹에 연결된 메뉴가 있습니다그룹 메뉴를 먼저 삭제 하시기 바랍니다.'); 
messageString.put('message_289', '보다 커야  합니다.'); 
messageString.put('message_290', '보다 작아야  합니다.'); 
messageString.put('message_291', '입력기간을 확인하십시요.'); 
messageString.put('message_292', '탈퇴처리  할 항목이 선택되지 않았습니다.'); 
messageString.put('message_293', '휴면처리  할 항목이 선택되지 않았습니다.'); 
messageString.put('message_294', '중복된 기간의 차시가 존재합니다.'); 
messageString.put('message_295', '파일 삭제시 오류가 발생하였습니다.'); 
messageString.put('message_296', '과제 확인 승인시 오류가 발생하였습니다.'); 
messageString.put('message_297', '아이디 값이 없습니다.'); 
messageString.put('message_298', '상대평가 정규분포 총 배분율이 100%가 아닙니다.'); 
messageString.put('message_299', '최대 비율이 100%를 넘을 수 없습니다.'); 
messageString.put('message_300', '소수점은 2자리 까지만 입력 가능합니다.'); 
messageString.put('message_301', '중복된 데이터가 존재합니다.'); 
messageString.put('message_302', '차례대로 입력하세요.'); 
messageString.put('message_303', '평가요소별 기본배분 총비율이 100%가 아닙니다.'); 
messageString.put('message_304', '길이를 확인하세요.'); 
messageString.put('message_305', '비밀번호는 아이디와 달라야 합니다.'); 
messageString.put('message_306', '비밀번호에 생년월일을 입력할 수 없습니다.'); 
messageString.put('message_307', '비밀번호확인과 비밀번호가다릅니다.'); 
messageString.put('message_308', '상호 승인이 끝났으므로 수정할 수 없습니다.'); 
messageString.put('message_309', '선택해 주세요.'); 
messageString.put('message_310', '이미 추가되어 있습니다.'); 
messageString.put('message_311', '삭제 할 수 없습니다.'); 
messageString.put('message_312', '다시 선택해 주세요.'); 
messageString.put('message_313', '회원구분 변경을 할 수 없습니다.'); 
messageString.put('message_314', '입력하신 정보와 일치하는 아이디가 존재하지 않습니다. 입력하신 정보를 확인하십시오.'); 
messageString.put('message_315', '14세이상은 학생 회원가입대상이 아닙니다.'); 
messageString.put('message_316', '14세미만은 학생 회원가입대상입니다.'); 
messageString.put('message_317', '14세이상의 부모동의가 필요합니다.'); 
messageString.put('message_318', '수강신청할 수 있는 그룹이 아닙니다.강좌설명을 통해 수강신청 가능그룹을 확인하십시요.'); 
messageString.put('message_319', '이미 수강신청하셨던 강좌입니다.'); 
messageString.put('message_320', '시스템 관리 데이터이므로 추가/수정/삭제할 수 없습니다.'); 
messageString.put('message_321', '기수의 교육기간이 종료된 경우 삭제할 수 없습니다.'); 
messageString.put('message_322', '시작년도는 검색한 년도와 동일해야합니다.'); 
messageString.put('message_323', '학생이 등록되어 있어 삭제할 수 없습니다.'); 
messageString.put('message_324', '그룹명이 중복되었습니다.'); 
messageString.put('message_325', '이미 학생이 등록되어 있습니다.승인대기를 확인하십시요'); 
messageString.put('message_326', '이미 부모님이 등록되어 있습니다.승인대기를 확인하십시요'); 
messageString.put('message_327', '이미 자녀가 등록되어 있습니다.승인대기를 확인하십시요'); 
messageString.put('message_328', '기수의 교육기간이 종료된 경우 추가할 수 없습니다.'); 
messageString.put('message_329', '14세 미만만 가입 가능합니다.'); 
messageString.put('message_330', '14세이상만 가입 가능합니다.'); 
messageString.put('message_331', '과정분류의 데이터가 변경되어 작업이 진행될수 없습니다.변경된 과정분류에 로드합니다.'); 
messageString.put('message_332', '해당 과정분류에 강좌가 존재합니다.강좌를 삭제 후 과정을 삭제하시기 바랍니다.'); 
messageString.put('message_333', '해당 과정분류에 학력진단 문항이 존재합니다.학력진단 시스템의 문항 삭제 후 과정을 삭제하시기 바랍니다.'); 
messageString.put('message_334', '설문응시생이 존재하여 설문을 수정할 수 없습니다.'); 
messageString.put('message_335', '강좌의 교육기간이 종료된 경우 차시순서를 변경할 수 없습니다.'); 
messageString.put('message_336', '교육시작일자가 종료일자보다 클 수 없습니다.'); 
messageString.put('message_337', '교육종료일자가 현재일자보다 작을 수 없습니다.'); 
messageString.put('message_338', '교육과정분류를 선택하세요!'); 
messageString.put('message_339', '수강가능 그룹을 선택하세요!'); 
messageString.put('message_340', '수료증 번호를 입력하세요!'); 
messageString.put('message_341', '수료증 번호 중복 확인 버튼을 눌러주세요!'); 
messageString.put('message_342', '이미 등록된 수료증 번호입니다.'); 
messageString.put('message_343', '오늘의 인증횟수 2회를 초과하셨습니다.'); 
messageString.put('message_344', '바이트를 초과하였습니다.'); 
messageString.put('message_345', '사진등록은 JPG, GIF, PNG, BMP, TIF 파일만 등록 가능합니다.'); 
messageString.put('message_346', '이미 학교 관리자로 등록 되어있습니다.'); 
messageString.put('message_347', '회원상태가 가입, 가입대기, 휴면인 경우만 탈퇴처리 할 수 있습니다.'); 
messageString.put('message_348', '회원상태가 가입, 가입대기인 경우만 휴면처리 할 수 있습니다.'); 
messageString.put('message_349', '회원상태가 가입대기인 경우만 가입처리 할 수 있습니다.'); 
messageString.put('message_350', '가입처리  할 항목이 선택되지 않았습니다.'); 
messageString.put('message_351', '쪽지를 보낼 친구가 선택되지 않았습니다.'); 
messageString.put('message_352', '영재회원 신청이 완료되었습니다.'); 
messageString.put('message_353', '이미 영재회원 신청이 되어 있습니다.'); 
messageString.put('message_354', '영재회원 등록회원이십니다..'); 
messageString.put('message_355', '학생만 영재회원 신청을 할 수 있습니다..'); 
messageString.put('message_356', '시험점수를 저장하였습니다.'); 
messageString.put('message_357', '기수의 오프라인차시 일정정보가 존재하는 경우 삭제할 수 없습니다.'); 
messageString.put('message_358', '시험응시 여부를  저장하였습니다.'); 
messageString.put('message_359', '맛보기가 존재하지 않습니다.'); 
messageString.put('message_360', ''-' 는 첫글자에만 올 수 있습니다'); 
messageString.put('message_361', '학생 그룹이 등록되어 있지 않습니다. 그룹설정 버튼을 클릭하여 학생 그룹을 등록해 주십시오. '); 
messageString.put('message_362', '영재학생에게만  제공하는 메뉴입니다. 영재학생이 아닐경우 메뉴에 접근할 수 없습니다.'); 
messageString.put('message_363', '교직원에게만  제공하는 메뉴입니다. 교직원이 아닐경우 메뉴에 접근할 수 없습니다.'); 
messageString.put('message_364', '그룹변경 할 친구가 선택되지 않았습니다'); 
messageString.put('message_365', '친구가 등록되어 있어 삭제할 수 없습니다.'); 
messageString.put('message_366', '선택된 친구에게 메일을 발송하였습니다.'); 
messageString.put('message_367', '현재 순서이동 작업이 진행중입니다.순서이동 작업을 완료하신 후 실행해 주십시요.'); 
messageString.put('message_368', '현재 다른 노드의 순서이동 작업이 진행중입니다.순서이동 작업을 완료하신 후 실행해 주십시요.'); 
messageString.put('message_369', '업로드할 수 없는 확장자 파일입니다.'); 
messageString.put('message_370', '최대 허용된 용량을 초과하였습니다.'); 
messageString.put('message_371', '플래쉬 버전이 8.0 이상인지 확인하세요. 이미 설치하신 경우는 브라우저를 전부 닫고 다시 시작하세요.'); 
messageString.put('message_372', '네트워크 에러가 발생하였습니다. 관리자에게 문의하세요.'); 
messageString.put('message_373', '입출력 에러가 발생하였습니다. 다른 프로그램에서 이 파일을 사용중인지 확인하세요.'); 
messageString.put('message_374', '보안 에러가 발생하였습니다. 관리자에게 문의하세요.'); 
messageString.put('message_375', '요청하신 페이지가 존재하지 않습니다.'); 
messageString.put('message_376', '이메일 형식이 잘못되었습니다.'); 
messageString.put('message_377', '삭제할 수 없는 공통코드입니다.'); 
messageString.put('message_378', '하위 공통코드가 존재하므로 삭제할수 없습니다.');
messageString.put('message_379', '입력하신 아이디의 중복체크가 되지 않았습니다.');
messageString.put('message_380', '고객번호 확인이  되지 않았습니다.');
messageString.put('message_381', '이미 가입 된 주민등록번호 입니다');
messageString.put('message_382', '가입이 가능한 주민등록번호 입니다');
messageString.put('message_383', '사용할 수 있는 아이디 입니다.');
messageString.put('message_384', '사용할 수 없는 고객번호 입니다.');
messageString.put('message_385', '사용할 수 있는 고객번호 입니다.');
messageString.put('message_386', '이용약관 및 개인정보취급 방침에 동의하여 주십시오.');
messageString.put('message_387', '이미 가입 된 외국인등록번호 입니다.');
messageString.put('message_388', '가입이 가능한 외국인등록번호 입니다.');
messageString.put('message_389', '입력사항 사실여부를 확인하여 주십시오.');
messageString.put('message_390', '중복되는 수치의 부하임계 정보가 존재합니다.부하임계 정보를 다시 입력하여 주십시오.');
messageString.put('message_391', '비밀번호의 길이가 6자 미만입니다.');
messageString.put('message_392', '아이디의 길이가 4자 미만입니다.');
messageString.put('message_393', '아이디가 입력되지 않았습니다.');
messageString.put('message_394', '기존의 XML 파일이 갱신됩니다. XML파일을 생성하시겠습니까?');
messageString.put('message_395', '새로운 XML 파일이 생성되었습니다.');
messageString.put('message_396', '콘텐츠를 업로드 하셔야 콘텐츠 정보가 저장됩니다.');

var	message	= {
		get : function(messageCode) {
			messageCode	+= '';
			var	result = ' 해당	코드가 없습니다.';
			if (!messageString.containsKey(messageCode)) {
				return result;
			}
			var	size = messageString.keys();
			try	{
				result = messageString.get(messageCode);
			}
			catch (e) {}
			return result.replace(//g,	'');
		}
	}

