    
CREATE TABLE TB_DEMY (
	TEST1 NUMBER(9),
	TEST2 VARCHAR(20),
	TEST3 NUMBER(11),
	TEST4 BLOB,
	TEST5 NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
    
CREATE TABLE TB_DEMYS1 (
	TEST1 NUMBER(9),
	TEST2 VARCHAR(20),
	TEST3 NUMBER(11),
	TEST4 BLOB,
	TEST5 NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
    
CREATE TABLE TB_LCMS_CMI_COMMENTFROMLMS (
	COMMENTS_LMS_COMMENT_SEQ NUMBER(9) DEFAULT 0,
	COMMENTS_LMS_COUNT NUMBER(9) DEFAULT 0,
	COMMENTS_LMS_COMMENT VARCHAR(4000),
	COMMENTS_LMS_LOCATION VARCHAR(2000),
	COMMENTS_LMS_TIMESTAMP VARCHAR(500),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	COURSE_MAP_SEQ NUMBER(11),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	LEARNER_ID VARCHAR(50)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_COMMENTFROMLMS IS '코멘트'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COMMENTS_LMS_COMMENT_SEQ IS 'LMS코멘트_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COMMENTS_LMS_COUNT IS 'LMS코멘트수'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COMMENTS_LMS_COMMENT IS 'LMS코멘트'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COMMENTS_LMS_LOCATION IS 'LMS위치정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COMMENTS_LMS_TIMESTAMP IS '학습자코멘트_타임스템프'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTFROMLMS.LEARNER_ID IS '학습자ID'
;

    
CREATE TABLE TB_LCMS_CMI_COMMENTLEARNER (
	COMMENTS_LEARNER_CMT_SEQ NUMBER(9) DEFAULT 0,
	CMTS_LEARNER_COUNT NUMBER(9) DEFAULT 0,
	CMTS_LEARNER_CMT VARCHAR(4000),
	CMTS_LEARNER_LOCATION VARCHAR(2000),
	CMTS_LEARNER_DATA VARCHAR(600),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	CMTS_LEARNER_NUM NUMBER(9),
	PROGRESSCODE NUMBER(9),
	COURSE_MAP_SEQ NUMBER(11),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	LEARNER_ID VARCHAR(50),
	CMTS_LEARNER_TIMESTAMP VARCHAR(600)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_COMMENTLEARNER IS '학습자코멘트'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.COMMENTS_LEARNER_CMT_SEQ IS '학습자코멘트_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_COUNT IS '학습자코멘트_코멘트수'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_CMT IS '학습자코멘트_코멘트'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_LOCATION IS '학습자코멘트_위치정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_DATA IS '학습자코멘트_정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_NUM IS '학습자코맨트_순번'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.PROGRESSCODE IS 'PROGRESSCODE'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.LEARNER_ID IS '학습자ID'
;
COMMENT ON COLUMN TB_LCMS_CMI_COMMENTLEARNER.CMTS_LEARNER_TIMESTAMP IS '학습자코멘트_위치정보(소스상에존재 추가 정확하게 알수없음 )'
;

    
CREATE TABLE TB_LCMS_CMI_IA (
	INTERACTIONS_SEQ NUMBER(9),
	INTERACTIONS_COUNT NUMBER(9),
	INTERACTIONS_ID VARCHAR(4000),
	INTERACTIONS_TYPE VARCHAR(50),
	INTERACTIONS_WEIGHTING VARCHAR(50),
	INTERACTIONS_LEARNER_RESPONSE VARCHAR(500),
	INTERACTIONS_RESULT VARCHAR(50),
	INTERACTIONS_LATENCY VARCHAR(1450),
	INTERACTIONS_DESCRIPTION VARCHAR(1450),
	INTERACTIONS_TIMESTAMP VARCHAR(50),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	COURSE_MAP_SEQ NUMBER(11),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	LEARNER_ID VARCHAR(50)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_IA IS '상호작용'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_SEQ IS '상호작용_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_COUNT IS '상호작용_갯수'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_ID IS '상호작용_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_TYPE IS '상호작용_유형'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_WEIGHTING IS '상호작용_무게'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_LEARNER_RESPONSE IS '상호작용_학습자반응'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_RESULT IS '상호작용_결과값'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_LATENCY IS '상호작용_지체시간'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_DESCRIPTION IS '상호작용_설명'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.INTERACTIONS_TIMESTAMP IS '상호작용 시간'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_IA.LEARNER_ID IS '학습자ID'
;

    

    
CREATE TABLE TB_LCMS_CMI_OBJECTCOMMONINFO (
	SEQ NUMBER(9),
	VERSION VARCHAR(100),
	COMMENTS_FROM_LEARNER_CHILDREN VARCHAR(100),
	COMMENTS_FROM_LMS_CHILDREN VARCHAR(100),
	INTERACTIONS_CHILDREN VARCHAR(200),
	LEARNER_PREFERENCE_CHILDREN VARCHAR(100),
	OBJECTIVES_CHILDREN VARCHAR(100),
	OBJECTIVES_SCORE_CHILDREN VARCHAR(100),
	SCORE_CHILDREN VARCHAR(100),
	USERID VARCHAR(20),
	UPDATE_DT DATE
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_OBJECTCOMMONINFO IS '스콤객체공통정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.SEQ IS 'LCMS고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.VERSION IS '버젼'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.COMMENTS_FROM_LEARNER_CHILDREN IS '학습자코맨트_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.COMMENTS_FROM_LMS_CHILDREN IS 'LMS코맨트_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.INTERACTIONS_CHILDREN IS '상호작용_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.LEARNER_PREFERENCE_CHILDREN IS '학습자선호도_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.OBJECTIVES_CHILDREN IS '학습목표_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.OBJECTIVES_SCORE_CHILDREN IS '학습목표기준점수_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.SCORE_CHILDREN IS '준거점수_산물'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTCOMMONINFO.UPDATE_DT IS '갱신일자'
;


    
CREATE TABLE TB_LCMS_CMI_OBJECTINFO (
	COURSE_MAP_SEQ NUMBER(11),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	LEARNER_ID VARCHAR(50),
	LEARNER_NAME VARCHAR(50),
	TOTAL_TIME VARCHAR(50),
	SCORE_SCALED VARCHAR(50),
	COMPLETION_STATUS VARCHAR(50),
	COMPLETION_THRESHOLD VARCHAR(50),
	ENTRY_INFO VARCHAR(50),
	CREDIT VARCHAR(50),
	EXIT_STATUS VARCHAR(50),
	LAUNCH_DATA VARCHAR(500),
	LOCATION VARCHAR(4000),
	MAX_TIME_ALLOWED VARCHAR(50),
	MODE_INFO VARCHAR(50),
	PROGRESS_MEASURE VARCHAR(50),
	SCALED_PASSING_SCORE VARCHAR(50),
	SUCCESS_STATUS VARCHAR(50),
	SUSPEND_DATA VARCHAR(4000),
	TIME_LIMIT_ACTION VARCHAR(50),
	SCORE_RAW VARCHAR(50),
	SCORE_MAX VARCHAR(50),
	SCORE_MIN VARCHAR(50),
	LEARNER_PREFERENCE_AUDIO_LEVEL VARCHAR(50),
	LEARNER_PREFERENCE_LANGUAGE VARCHAR(500),
	LEARNER_PREFERENCE_DELIVERY_SP VARCHAR(50),
	LEARNER_PREFERENCE_AUDIO_CAPTI VARCHAR(50),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	ATTEMPT NUMBER(10) DEFAULT 0,
	COURSE_CD NUMBER,
	COMPLETED_DT DATE
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_OBJECTINFO IS 'SCORM2004_객체정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_ID IS '학습자ID'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_NAME IS '학습자명'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.TOTAL_TIME IS '총학습시간'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SCORE_SCALED IS '최종점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.COMPLETION_STATUS IS '완료_상태'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.COMPLETION_THRESHOLD IS '완료준거기준'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.ENTRY_INFO IS '엔트리'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.CREDIT IS '크레디트'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.EXIT_STATUS IS '종료_상태'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LAUNCH_DATA IS '탑재데이터'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LOCATION IS '위치정보'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.MAX_TIME_ALLOWED IS '최대허용학습시간'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.MODE_INFO IS '학습모드'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.PROGRESS_MEASURE IS '진도율'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SCALED_PASSING_SCORE IS '최종합격점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SUCCESS_STATUS IS '합격상태'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SUSPEND_DATA IS '보류데이타'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.TIME_LIMIT_ACTION IS '시간초과시액션'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SCORE_RAW IS '원시점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SCORE_MAX IS '최대점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.SCORE_MIN IS '최저점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_PREFERENCE_AUDIO_LEVEL IS '학습자선호도_오디오레벨'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_PREFERENCE_LANGUAGE IS '학습자선호도_언어'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_PREFERENCE_DELIVERY_SP IS '학습자선호도_전달속도'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.LEARNER_PREFERENCE_AUDIO_CAPTI IS '학습자선호도_오디오캡션닝'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.ATTEMPT IS '시도횟수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTINFO.COMPLETED_DT IS '학습완료일자'
;

    
CREATE TABLE TB_LCMS_CMI_OBJECTIVES (
	OBJECTIVES_SEQ NUMBER(9),
	OBJECTIVES_COUNT NUMBER(9),
	OBJECTIVES_ID VARCHAR(4000),
	OBJECTIVES_SCORE_SCALED VARCHAR(50),
	OBJECTIVES_SCORE_RAW VARCHAR(50),
	OBJECTIVES_SCORE_MIN VARCHAR(50),
	OBJECTIVES_SCORE_MAX VARCHAR(50),
	OBJECTIVES_SUCCESS_STATUS VARCHAR(50),
	OBJECTIVES_COMPLETION_STATUS VARCHAR(50),
	OBJECTIVES_PROGRESS_MEASURE VARCHAR(50),
	OBJECTIVES_DESCRIPTION VARCHAR(2000),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	COURSE_MAP_SEQ NUMBER(11),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	LEARNER_ID VARCHAR(50)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_CMI_OBJECTIVES IS '학습목표'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SEQ IS '개별목표_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_COUNT IS '학습목표_카운트'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_ID IS '학습목표_ID'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SCORE_SCALED IS '학습목표_최종측정점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SCORE_RAW IS '학습목표_원시점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SCORE_MIN IS '학습목표_최저점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SCORE_MAX IS '학습목표_최대점수'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_SUCCESS_STATUS IS '학습목표_합격상태'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_COMPLETION_STATUS IS '학습목표_완료_상태'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_PROGRESS_MEASURE IS '학습목표_진도_측정값'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.OBJECTIVES_DESCRIPTION IS '학습목표_설명'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_CMI_OBJECTIVES.LEARNER_ID IS '학습자ID'
;


    
CREATE TABLE TB_LCMS_COURSE_MAP (
	COURSE_MAP_SEQ NUMBER(11),
	SUBJ VARCHAR2(10),
	YEAR VARCHAR2(4),
	SUBJSEQ VARCHAR2(4),
	LMS_YEAR VARCHAR(4),
	LMS_TERM VARCHAR(32),
	LMS_WEEK_CD VARCHAR(20),
	LMS_COURSE_CD VARCHAR(64),
	SERVICE_YN CHAR(1),
	YN_LMS CHAR(1),
	LMS_SUBJECT_CD VARCHAR(64),
	ORG_SEQ NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_COURSE_MAP IS '과정맴핑'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.COURSE_MAP_SEQ IS '과정코드'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.COURSE_MAP_SEQ IS '년도'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.COURSE_MAP_SEQ IS '과정차수'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.LMS_YEAR IS '과정년도'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.LMS_TERM IS 'LMS학기'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.LMS_WEEK_CD IS 'LMS 주차코드'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.LMS_COURSE_CD IS 'LMS 과정번호'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.SERVICE_YN IS '서비스여부'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.YN_LMS IS 'LMS 연계여부'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.LMS_SUBJECT_CD IS 'LMS 주차코드2'
;
COMMENT ON COLUMN TB_LCMS_COURSE_MAP.ORG_SEQ IS '학습주제_일련번호'
;


    
CREATE TABLE TB_LCMS_COURSE_ORG (
	ORG_SEQ NUMBER(9) DEFAULT 0,
	SUBJ VARCHAR2(10),
	USERID VARCHAR(20),
	REG_DTTM CHAR(14),
	CRS_ORG_NO NUMBER(10)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_COURSE_ORG IS '과정차시정보'
;
COMMENT ON COLUMN TB_LCMS_COURSE_ORG.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_COURSE_ORG.SUBJ IS '과정코드'
;
COMMENT ON COLUMN TB_LCMS_COURSE_ORG.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_COURSE_ORG.REG_DTTM IS '등록일시'
;
COMMENT ON COLUMN TB_LCMS_COURSE_ORG.CRS_ORG_NO IS '학습주제별_일련번호'
;


    
CREATE TABLE TB_LCMS_FILE (
	LCMS_FILE_SEQ NUMBER(9),
	RSRC_SEQ NUMBER(18),
	FILE_HREF VARCHAR(100),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	META_LOCATION VARCHAR(2000)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_FILE IS '파일'
;
COMMENT ON COLUMN TB_LCMS_FILE.LCMS_FILE_SEQ IS 'LCMS파일고유번호'
;
COMMENT ON COLUMN TB_LCMS_FILE.RSRC_SEQ IS '학습자료_일련번호'
;
COMMENT ON COLUMN TB_LCMS_FILE.FILE_HREF IS '파일경로'
;
COMMENT ON COLUMN TB_LCMS_FILE.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_FILE.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_FILE.META_LOCATION IS '메타위치'
;


    
CREATE TABLE TB_LCMS_GLOBALOBJ (
	OBJID VARCHAR(255),
	USERID VARCHAR(20),
	SCOPEID VARCHAR(20),
	SATISFIED VARCHAR(20),
	MEASURE VARCHAR(10)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_GLOBALOBJ IS 'LCMS글로벌오브젝트'
;
COMMENT ON COLUMN TB_LCMS_GLOBALOBJ.OBJID IS '오브젝트아이디'
;
COMMENT ON COLUMN TB_LCMS_GLOBALOBJ.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_GLOBALOBJ.SCOPEID IS '적용아이디'
;
COMMENT ON COLUMN TB_LCMS_GLOBALOBJ.SATISFIED IS '통과여부'
;
COMMENT ON COLUMN TB_LCMS_GLOBALOBJ.MEASURE IS '점수'
;


    
CREATE TABLE TB_LCMS_ITEM (
	ITEM_SEQ NUMBER(9) DEFAULT 0,
	HIGH_ITEM_SEQ NUMBER(9) DEFAULT 0,
	ORG_ITEM_NO NUMBER(9) DEFAULT 0,
	ITEM_ID VARCHAR(256),
	ITEM_ID_REF VARCHAR(256),
	ITEM_TITLE VARCHAR(1000),
	ITEM_TYPE VARCHAR(5),
	ITEM_OPEN VARCHAR(5),
	ITEM_TL_ACTION CHAR(1),
	ITEM_MAX_TIME NUMBER,
	ITEM_START_FILE VARCHAR(256),
	ITEM_LOM_FILE VARCHAR(256),
	ITEM_PARAMETERS VARCHAR(1000),
	DATA_FROM_LMS VARCHAR(4000),
	ITEM_THRESHOLD VARCHAR(10),
	META_LOCATION VARCHAR(2000),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	RSRC_SEQ NUMBER(18),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	COURSE_CD VARCHAR(50),
	ITEM_PROGRESS_TIME NUMBER,
	BEFORE_ITEM_SEQ NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_ITEM IS '학습요소'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_SEQ IS '학습요소_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM.HIGH_ITEM_SEQ IS '상위요소_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ORG_ITEM_NO IS '주제별_요소_순번'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_ID_REF IS '학습요소_참조_아이디'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_TITLE IS '학습요소_제목'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_TYPE IS '학습요소_구분'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_OPEN IS '학습요소_사용여부'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_TL_ACTION IS '시간제한_처리'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_MAX_TIME IS '제한시간'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_START_FILE IS '학습요소_시작_파일'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_LOM_FILE IS '학습요소_메타_파일'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_PARAMETERS IS '학습요소_변수'
;
COMMENT ON COLUMN TB_LCMS_ITEM.DATA_FROM_LMS IS 'LMS_전달_값'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_THRESHOLD IS '임계치'
;
COMMENT ON COLUMN TB_LCMS_ITEM.META_LOCATION IS '메타위치'
;
COMMENT ON COLUMN TB_LCMS_ITEM.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_ITEM.RSRC_SEQ IS '학습자료_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM.COURSE_CD IS '과목코드'
;
COMMENT ON COLUMN TB_LCMS_ITEM.ITEM_PROGRESS_TIME IS '학습인정시간'
;
COMMENT ON COLUMN TB_LCMS_ITEM.BEFORE_ITEM_SEQ IS '이전학습객체고유번호'
;


    
CREATE TABLE TB_LCMS_ITEM_RESOURCE (
	RSRC_SEQ NUMBER(18),
	RSRC_TYPE VARCHAR(16),
	RSRC_HREF VARCHAR(100),
	RSRC_BASE_DIR VARCHAR(100),
	RSRC_SCORM_TYPE VARCHAR(10),
	RSRC_PST_STATE VARCHAR(5),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	RSRC_TITLE VARCHAR(128),
	RSRC_SCO_SIZE NUMBER(18),
	GROUP_SEQ NUMBER(9),
	RSRC_SCO_VERSION VARCHAR(10),
	RSRC_ID VARCHAR(255)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_ITEM_RESOURCE IS '학습요소_자료'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_SEQ IS '학습자료_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_TYPE IS '자료유형'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_HREF IS '자료파일명'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_BASE_DIR IS '자료_디렉토리_경로'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_SCORM_TYPE IS '스콤유형'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_PST_STATE IS '상태지정'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_TITLE IS '자료명'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_SCO_SIZE IS 'SCO파일SIZES'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.GROUP_SEQ IS '그룹고유번호'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_SCO_VERSION IS 'SCO버젼'
;
COMMENT ON COLUMN TB_LCMS_ITEM_RESOURCE.RSRC_ID IS '자료코드'
;


    
CREATE TABLE TB_LCMS_LESSON (
	SUBJ VARCHAR(10),
	MODULE VARCHAR(2),
	LESSON VARCHAR(4),
	LESSON_CD VARCHAR(10),
	OWNER VARCHAR(10),
	DEPTH NUMBER DEFAULT 1,
	ORDER_NUM NUMBER,
	LESSON_NAME VARCHAR(500),
	STARTING VARCHAR(200),
	EDU_TIME NUMBER DEFAULT 0,
	EDU_TIME_YN CHAR(1) DEFAULT 'N',
	PROGRESS_YN CHAR(1) DEFAULT 'Y',
	PAGE_COUNT NUMBER DEFAULT 0,
	INUSERID VARCHAR(20),
	INDATE DATE DEFAULT SYSDATE,
	LUSERID VARCHAR(20),
	LDATE DATE DEFAULT SYSDATE
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_LESSON IS '레스정보'
;
COMMENT ON COLUMN TB_LCMS_LESSON.SUBJ IS '과정코드'
;
COMMENT ON COLUMN TB_LCMS_LESSON.MODULE IS '모듈'
;
COMMENT ON COLUMN TB_LCMS_LESSON.LESSON IS '레슨'
;
COMMENT ON COLUMN TB_LCMS_LESSON.LESSON_CD IS '레슨코드'
;
COMMENT ON COLUMN TB_LCMS_LESSON.OWNER IS '상위코드'
;
COMMENT ON COLUMN TB_LCMS_LESSON.DEPTH IS '깊이'
;
COMMENT ON COLUMN TB_LCMS_LESSON.ORDER_NUM IS '정렬순서'
;
COMMENT ON COLUMN TB_LCMS_LESSON.LESSON_NAME IS '레슨명'
;
COMMENT ON COLUMN TB_LCMS_LESSON.STARTING IS '시작위치'
;
COMMENT ON COLUMN TB_LCMS_LESSON.EDU_TIME IS '수강시간'
;
COMMENT ON COLUMN TB_LCMS_LESSON.EDU_TIME_YN IS '수강시간설정여부'
;
COMMENT ON COLUMN TB_LCMS_LESSON.PROGRESS_YN IS '진도체크여부'
;
COMMENT ON COLUMN TB_LCMS_LESSON.PAGE_COUNT IS '페이지수'
;
COMMENT ON COLUMN TB_LCMS_LESSON.INUSERID IS '최초등록자'
;
COMMENT ON COLUMN TB_LCMS_LESSON.INDATE IS '최초등록일'
;
COMMENT ON COLUMN TB_LCMS_LESSON.LUSERID IS '최종수정자'
;
COMMENT ON COLUMN TB_LCMS_LESSON.LDATE IS '최종수정일'
;


    
CREATE TABLE TB_LCMS_MANISEQ (
	SEQ NUMBER(9),
	INSERT_DATE DATE
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_MANISEQ IS '콘텐츠등록순번'
;
COMMENT ON COLUMN TB_LCMS_MANISEQ.SEQ IS 'LCMS고유번호'
;
COMMENT ON COLUMN TB_LCMS_MANISEQ.INSERT_DATE IS '생성일'
;


    
CREATE TABLE TB_LCMS_MATERIAL (
	MAT_SEQ NUMBER(9),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	MAT_NAME VARCHAR(100),
	MAT_DESC VARCHAR(4000),
	UPLOAD_SEQ NUMBER(9),
	REG_DTTM CHAR(14),
	REG_SEQ NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_MATERIAL IS '학습보조자료'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.MAT_SEQ IS '보조자료일련번호'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.MAT_NAME IS '보조자료명'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.MAT_DESC IS '보조자료설명'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.UPLOAD_SEQ IS '파일고유번호'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.REG_DTTM IS '등록일시'
;
COMMENT ON COLUMN TB_LCMS_MATERIAL.REG_SEQ IS '등록자고유번호'
;


    
CREATE TABLE TB_LCMS_METADATA (
	METADATA_SEQ NUMBER(9),
	METATYPE VARCHAR(20),
	OBJ_SEQ NUMBER(9),
	OBJ_TYPE VARCHAR(20),
	COMMENTS VARCHAR(1500),
	USERID VARCHAR(20),
	TEMPLATE_SEQ NUMBER(9),
	REG_DTTM CHAR(14) DEFAULT sysdate
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_METADATA IS '메타데이터마스터'
;
COMMENT ON COLUMN TB_LCMS_METADATA.METADATA_SEQ IS '메타데이타 일련번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA.METATYPE IS '메타데이타 타입'
;
COMMENT ON COLUMN TB_LCMS_METADATA.OBJ_SEQ IS '오브제트 일련번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA.OBJ_TYPE IS '객체타입'
;
COMMENT ON COLUMN TB_LCMS_METADATA.COMMENTS IS '메타데이타 설명'
;
COMMENT ON COLUMN TB_LCMS_METADATA.USERID IS '회원고유번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA.TEMPLATE_SEQ IS '템플릿일련번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA.REG_DTTM IS '등록일시'
;


    
CREATE TABLE TB_LCMS_METADATA_ELEMENT (
	ELEMENT_SEQ NUMBER(9),
	ELEMENT_NAME VARCHAR(100),
	ELEMENT_VAL VARCHAR(1500),
	ELEMENT_PATH VARCHAR(200),
	LANG_VALUE VARCHAR(100),
	PRE_GROUP NUMBER(9),
	SELF_GROUP NUMBER(5),
	METADATA_SEQ NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_METADATA_ELEMENT IS '메타데이터 앨리먼트'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.ELEMENT_SEQ IS '엘리먼트 일련번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.ELEMENT_NAME IS '엘리먼트 이름'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.ELEMENT_VAL IS '엘리먼트 값'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.ELEMENT_PATH IS '엘리먼트 경로'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.LANG_VALUE IS 'language속성값'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.PRE_GROUP IS '상위그룹'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.SELF_GROUP IS '소속그룹'
;
COMMENT ON COLUMN TB_LCMS_METADATA_ELEMENT.METADATA_SEQ IS '메타데이타 일련번호'
;


    
CREATE TABLE TB_LCMS_METADATA_MAP (
	ELEMENT_PATH VARCHAR(200),
	METATYPE VARCHAR(20),
	OBJ_TYPE VARCHAR(20),
	SEARCH_YN CHAR(1),
	ELEMENT_NAME VARCHAR(100),
	ELEMENT_TITLE VARCHAR(100),
	READONLY CHAR(1),
	PRE_GROUP NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_METADATA_MAP IS '메타데이터맵정보'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.ELEMENT_PATH IS '엘리먼트 경로'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.METATYPE IS '메타데이타 타입'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.OBJ_TYPE IS '객체타입'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.SEARCH_YN IS '검색조건 설정'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.ELEMENT_NAME IS '엘리먼트 이름'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.ELEMENT_TITLE IS '엘리먼트 한글명'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.READONLY IS '읽기전용 설정'
;
COMMENT ON COLUMN TB_LCMS_METADATA_MAP.PRE_GROUP IS '상위그룹'
;


    
CREATE TABLE TB_LCMS_METADATA_TEMPLATE (
	TEMPLATE_SEQ NUMBER(9),
	TITLE VARCHAR(200),
	REG_SEQ NUMBER(9),
	REG_DTTM CHAR(14),
	OBJ_TYPE VARCHAR(20)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_METADATA_TEMPLATE IS '메타데이터템플릿'
;
COMMENT ON COLUMN TB_LCMS_METADATA_TEMPLATE.TEMPLATE_SEQ IS '템플릿일련번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA_TEMPLATE.TITLE IS '제목'
;
COMMENT ON COLUMN TB_LCMS_METADATA_TEMPLATE.REG_SEQ IS '등록자고유번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA_TEMPLATE.REG_DTTM IS '등록일시'
;
COMMENT ON COLUMN TB_LCMS_METADATA_TEMPLATE.OBJ_TYPE IS '객체타입'
;


    
CREATE TABLE TB_LCMS_METADATA_VOCA (
	VOCA_SEQ NUMBER(9),
	TITLE VARCHAR(200),
	REG_ID VARCHAR(20),
	REG_DTTM CHAR(14),
	OBJ_TYPE VARCHAR(20),
	ELEMENT_PATH VARCHAR(200)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_METADATA_VOCA IS '메타데이터_어휘록'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.VOCA_SEQ IS '어휘록고유번호'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.TITLE IS '제목'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.REG_ID IS '등록자아이디'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.REG_DTTM IS '등록일시'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.OBJ_TYPE IS '객체타입'
;
COMMENT ON COLUMN TB_LCMS_METADATA_VOCA.ELEMENT_PATH IS '엘리먼트 경로'
;


    
CREATE TABLE TB_LCMS_MODULE (
	SUBJ VARCHAR(10),
	MODULE VARCHAR(2),
	MODULE_NAME VARCHAR(500),
	INUSERID VARCHAR(20),
	INDATE DATE DEFAULT SYSDATE,
	LUSERID VARCHAR(20),
	LDATE DATE DEFAULT SYSDATE
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_MODULE IS '모듈정보'
;
COMMENT ON COLUMN TB_LCMS_MODULE.SUBJ IS '과정코드'
;
COMMENT ON COLUMN TB_LCMS_MODULE.MODULE IS '모듈'
;
COMMENT ON COLUMN TB_LCMS_MODULE.MODULE_NAME IS '모듈명'
;
COMMENT ON COLUMN TB_LCMS_MODULE.INUSERID IS '최초등록자'
;
COMMENT ON COLUMN TB_LCMS_MODULE.INDATE IS '최초등록일'
;
COMMENT ON COLUMN TB_LCMS_MODULE.LUSERID IS '최종수정자'
;
COMMENT ON COLUMN TB_LCMS_MODULE.LDATE IS '최종수정일'
;


    
CREATE TABLE TB_LCMS_ORGANIZATION (
	ORG_SEQ NUMBER(9) DEFAULT 0,
	COURSE_TYPE VARCHAR(6),
	ORG_ID VARCHAR(256),
	ORG_TITLE VARCHAR(255),
	ORG_DIR VARCHAR(30),
	CRS_ORG_NO NUMBER(10) DEFAULT 0,
	ORG_STRUCTURE VARCHAR(20),
	ORG_GLOBAL_TO_SYS VARCHAR(5),
	META_LOCATION VARCHAR(2000),
	USERID VARCHAR(20),
	UPDATE_DT DATE,
	ORG_STUDY_WIDTH NUMBER(9),
	ORG_STUDY_HEIGHT NUMBER(9),
	ORG_TREE_VIEW CHAR(1),
	ORG_WINDOW_FULL_VIEW CHAR(1),
	ORG_BUTTON_VIEW CHAR(1),
	ORG_SHOWTOPBTM_YN CHAR(1),
	ORG_CONTENTS_WIDTH NUMBER(4),
	ORG_CONTENTS_HEIGHT NUMBER(4),
	COURSE_CD VARCHAR(50),
	GROUP_SEQ NUMBER(9),
	MODEL_INFO VARCHAR(10)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_ORGANIZATION IS '학습주제'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.COURSE_TYPE IS '과정유형'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_ID IS '학습주제_아이디'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_TITLE IS '학습주제_제목'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_DIR IS '디렉토리경로'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.CRS_ORG_NO IS '학습주제별_일련번호'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_STRUCTURE IS '학습주제_구조'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_GLOBAL_TO_SYS IS '시스템 전역 객체'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.META_LOCATION IS '메타위치'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_STUDY_WIDTH IS '학습주제가로크기'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_STUDY_HEIGHT IS '학습주제세로크기'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_TREE_VIEW IS '학습트리표시여부'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_WINDOW_FULL_VIEW IS '학습창최대화'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_BUTTON_VIEW IS '버튼표시여부'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_SHOWTOPBTM_YN IS '상하부표시여부'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_CONTENTS_WIDTH IS '컨텐츠영역가로'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.ORG_CONTENTS_HEIGHT IS '컨텐츠영역세로'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.COURSE_CD IS '과목코드'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.GROUP_SEQ IS '그룹고유번호'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION.MODEL_INFO IS '학습모형'
;


    
CREATE TABLE TB_LCMS_ORGANIZATION_LOG (
	LOG_SEQ NUMBER(18),
	UPDATE_DT DATE,
	UPDATE_ID VARCHAR(50),
	INSERT_ID VARCHAR(50),
	ORG_SEQ NUMBER(9) DEFAULT 0
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_ORGANIZATION_LOG IS '학습주제변경이력'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION_LOG.LOG_SEQ IS '이력고유번호'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION_LOG.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION_LOG.UPDATE_ID IS '수정자아이디'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION_LOG.INSERT_ID IS '로그아이디'
;
COMMENT ON COLUMN TB_LCMS_ORGANIZATION_LOG.ORG_SEQ IS '학습주제_일련번호'
;


    
CREATE TABLE TB_LCMS_PROGRESS (
	SUBJ VARCHAR2(10),
	YEAR VARCHAR2(4),
	SUBJSEQ VARCHAR2(4),
	MODULE VARCHAR(2),
	LESSON VARCHAR(4),
	USERID VARCHAR(20),
	LESSONSTATUS CHAR(1) DEFAULT 'N',
	SESSION_TIME VARCHAR(20),
	TOTAL_TIME VARCHAR(20),
	LESSON_COUNT NUMBER(4),
	LOCATION VARCHAR(50),
	INDATE VARCHAR(14),
	INUSERID VARCHAR(20),
	LDATE VARCHAR(14),
	LUSERID VARCHAR(20)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.SUBJ IS '과정코드'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.YEAR IS '년도'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.SUBJSEQ IS '과정차수'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.MODULE IS '컨텐츠차시코드'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LESSON IS '컨텐츠레슨코드'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LESSONSTATUS IS '학습상태'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.SESSION_TIME IS '접속시간'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.TOTAL_TIME IS '총시간'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LESSON_COUNT IS '학습횟수'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LOCATION IS '페이지명'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.INDATE IS '등록일'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.INUSERID IS '등록자'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LDATE IS '수정일'
;
COMMENT ON COLUMN TB_LCMS_PROGRESS.LUSERID IS '수정자'
;

    
CREATE TABLE TB_LCMS_REPOSITORY_CATEGORY (
	REP_SEQ NUMBER(18),
	REP_NAME VARCHAR(20)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_REPOSITORY_CATEGORY IS '저장소분류'
;
COMMENT ON COLUMN TB_LCMS_REPOSITORY_CATEGORY.REP_SEQ IS '저장소분류_일련번호'
;
COMMENT ON COLUMN TB_LCMS_REPOSITORY_CATEGORY.REP_NAME IS '저장소분류_제목'
;


    
CREATE TABLE TB_LCMS_RESOURCE_DEPENDENCY (
	SEQ NUMBER(9) DEFAULT 0,
	RSRC_ID_REF VARCHAR(100),
	RSRC_SEQ NUMBER(18),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_RESOURCE_DEPENDENCY IS '자료그룹'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_DEPENDENCY.SEQ IS 'LCMS고유번호'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_DEPENDENCY.RSRC_ID_REF IS '자료_참조_ID'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_DEPENDENCY.RSRC_SEQ IS '학습자료_일련번호'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_DEPENDENCY.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_DEPENDENCY.UPDATE_DT IS '갱신일자'
;


    
CREATE TABLE TB_LCMS_RESOURCE_FORMATION (
	SEQ NUMBER(9),
	RSRC_SEQ NUMBER(18),
	FILE_VERSION VARCHAR(10),
	FILE_BASE_DIR VARCHAR(500),
	FILE_NAME VARCHAR(200),
	RE_COMMENT VARCHAR(4000),
	UPDATE_ID VARCHAR(50),
	UPDATE_DT DATE,
	OLD_FILE_VERSION VARCHAR(10)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_RESOURCE_FORMATION IS '자료형상관리'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.SEQ IS 'LCMS고유번호'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.RSRC_SEQ IS '학습자료_일련번호'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.FILE_VERSION IS '파일버젼'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.FILE_BASE_DIR IS '파일디렉토리'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.FILE_NAME IS '파일명'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.RE_COMMENT IS '변경사유'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.UPDATE_ID IS '수정자아이디'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_RESOURCE_FORMATION.OLD_FILE_VERSION IS '구파일버전'
;


    
CREATE TABLE TB_LCMS_RTE_CONFIG (
	ORG_SEQ NUMBER(9) DEFAULT 0,
	TREE_USE CHAR(1),
	NAV_USE CHAR(1),
	TITLE_USE CHAR(1),
	WIN_WIDTH NUMBER(9),
	WIN_HEIGHT NUMBER(9),
	COURSE_CD VARCHAR(50)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_RTE_CONFIG IS '학습창설정'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.TREE_USE IS '트리사용여부'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.NAV_USE IS '버튼사용여부'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.TITLE_USE IS '타이틀사용여부'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.WIN_WIDTH IS '윈도우가로크기'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.WIN_HEIGHT IS '윈도우세로크기'
;
COMMENT ON COLUMN TB_LCMS_RTE_CONFIG.COURSE_CD IS '과목코드'
;


    
CREATE TABLE TB_LCMS_RTE_LOG (
	LOG_SEQ NUMBER(18),
	SESSION_KEY VARCHAR(255),
	COURSE_MAP_SEQ NUMBER(11),
	USERID VARCHAR(20),
	ITEM_ID VARCHAR(256),
	STATUS VARCHAR(20),
	REG_DATE DATE,
	PROGRESS_MEASURE VARCHAR(50),
	TOTAL_TIME VARCHAR(50),
	ATTEMPT NUMBER(10),
	USER_IP VARCHAR(15)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_RTE_LOG IS '학습로그'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.LOG_SEQ IS '이력고유번호'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.SESSION_KEY IS '세션값'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.ITEM_ID IS '학습요소_아이디'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.STATUS IS '상태'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.REG_DATE IS '생성일시'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.PROGRESS_MEASURE IS '진도율'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.TOTAL_TIME IS '총학습시간'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.ATTEMPT IS '시도횟수'
;
COMMENT ON COLUMN TB_LCMS_RTE_LOG.USER_IP IS '사용자아이피'
;


    
CREATE TABLE TB_LCMS_RTE_THEME (
	THEME_SEQ NUMBER(9),
	TITLE VARCHAR(200),
	THEME_DIR VARCHAR(100),
	STUDY_WIDTH NUMBER(9),
	STUDY_HEIGHT NUMBER(9),
	REG_ID VARCHAR(20),
	REG_DT DATE,
	TITLE_HEIGHT NUMBER(9),
	TREE_WIDTH NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_RTE_THEME IS '학습창테마'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.THEME_SEQ IS '테마고유번호'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.TITLE IS '제목'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.THEME_DIR IS '테마디렉토리'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.STUDY_WIDTH IS '학습창가로크기'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.STUDY_HEIGHT IS '학습창세로크기'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.REG_ID IS '등록자아이디'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.REG_DT IS '테마등록일'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.TITLE_HEIGHT IS '타이틀크기'
;
COMMENT ON COLUMN TB_LCMS_RTE_THEME.TREE_WIDTH IS '트리가로크기'
;


    
CREATE TABLE TB_LCMS_SCORM_SEQUENCE (
	SEQ_IDX_NUM NUMBER(9) DEFAULT 0,
	ITEM_SEQ NUMBER(9) DEFAULT 0,
	ORG_SEQ NUMBER(9) DEFAULT 0,
	SEQ_ID VARCHAR(20),
	SEQ_IDREF VARCHAR(50),
	CHOICE VARCHAR(5),
	CHOICE_EXIT VARCHAR(5),
	FLOW VARCHAR(5),
	FORWARD_ONLY VARCHAR(5),
	USE_ATTEMPT_OBJ_INFO VARCHAR(5),
	USE_ATTEMPT_PROGRESS_INFO VARCHAR(5),
	ATTEMPT_LIMIT NUMBER(9) DEFAULT 0,
	ATTEMPT_DURATION_LIMIT VARCHAR(20),
	RANDOM_TIMING VARCHAR(20),
	SELECT_COUNT NUMBER(9) DEFAULT 0,
	REORDER_CHILDREN VARCHAR(5),
	SELECTION_TIMING VARCHAR(20),
	TRACKED VARCHAR(5),
	COMPLET_SETBY_CONTENT VARCHAR(5),
	OBJ_SETBY_CONTENT VARCHAR(5),
	PREVENT_ACTIVATION VARCHAR(5),
	CONSTRAIN_CHOICE VARCHAR(5),
	REQUIRED_SATISFIED VARCHAR(20),
	REQUIRED_NOT_SATISFIED VARCHAR(20),
	REQUIRED_COMPLETED VARCHAR(20),
	REQUIRED_INCOMPLETED VARCHAR(20),
	MEASURE_SATISFI_IF_ACTION VARCHAR(20),
	ROLLUP_OBJ_SATISFIED VARCHAR(5),
	ROLLUP_PROGRESS_COMPLETION VARCHAR(5),
	OBJ_MEASURE_WEIGHT VARCHAR(10),
	HIDE_UI_PRE VARCHAR(20),
	HIDE_UI_CON VARCHAR(20),
	HIDE_UI_EX VARCHAR(20),
	HIDE_UI_ABD VARCHAR(20),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	COURSE_CD VARCHAR(50),
	BEFORE_SEQ_IDX_NUM NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SCORM_SEQUENCE IS '스콤_계열화'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.SEQ_IDX_NUM IS '시퀀스고유번호'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ITEM_SEQ IS '학습요소_일련번호'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ORG_SEQ IS '학습주제_일련번호'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.SEQ_ID IS '아이디'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.SEQ_IDREF IS '아이디참조'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.CHOICE IS '선택'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.CHOICE_EXIT IS '선택종료'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.FLOW IS '흐름'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.FORWARD_ONLY IS '포워드'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.USE_ATTEMPT_OBJ_INFO IS '학습목표정보사용'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.USE_ATTEMPT_PROGRESS_INFO IS '진행상태정보사용'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ATTEMPT_LIMIT IS '시도제한'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ATTEMPT_DURATION_LIMIT IS '시도주기제한'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.RANDOM_TIMING IS '랜덤발생시간'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.SELECT_COUNT IS '선택된자식학습활동수'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.REORDER_CHILDREN IS '자식학습활동순서'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.SELECTION_TIMING IS '선택발생시간'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.TRACKED IS '추적기록'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.COMPLET_SETBY_CONTENT IS '학습활동단위완료여부'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.OBJ_SETBY_CONTENT IS '학습목표만족여부'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.PREVENT_ACTIVATION IS '자식학습활동제한'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.CONSTRAIN_CHOICE IS '학습활동선택제한'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.REQUIRED_SATISFIED IS '만족조건요청'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.REQUIRED_NOT_SATISFIED IS '불만족조건요청'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.REQUIRED_COMPLETED IS '완료조건요청'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.REQUIRED_INCOMPLETED IS '미완료조건요청'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.MEASURE_SATISFI_IF_ACTION IS '학습활동중평가사용여부'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ROLLUP_OBJ_SATISFIED IS '롤업_학습목표_만족평가'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.ROLLUP_PROGRESS_COMPLETION IS '롤업_진도_완료'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.OBJ_MEASURE_WEIGHT IS '학습목표_준거점수_가중치'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.HIDE_UI_PRE IS '이전버튼_숨김'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.HIDE_UI_CON IS '다음버튼_숨김'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.HIDE_UI_EX IS '종료버튼_숨김'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.HIDE_UI_ABD IS '일단정지버튼_숨김'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.COURSE_CD IS '과목코드'
;
COMMENT ON COLUMN TB_LCMS_SCORM_SEQUENCE.BEFORE_SEQ_IDX_NUM IS '이전객체번호'
;


    
CREATE TABLE TB_LCMS_SEQ_CONDITION_TYPE (
	CT_IDX_NUM NUMBER(9) DEFAULT 0,
	SEQ_ID_NUM NUMBER(9),
	RULE_CONDITION_ID NUMBER(9) DEFAULT 0,
	CONDITION_RULE_TYPE VARCHAR(4),
	RULE_ACTION VARCHAR(20),
	CONDITION_COMBINATION VARCHAR(20),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	SEQ_IDX_NUM NUMBER(9) DEFAULT 0,
	BEFORE_CT_IDX_NUM NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_CONDITION_TYPE IS '규칙조건타입'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.CT_IDX_NUM IS '규칙조건타입번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.SEQ_ID_NUM IS '시퀀스아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.RULE_CONDITION_ID IS '규칙조건집합아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.CONDITION_RULE_TYPE IS '규칙조건타입'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.RULE_ACTION IS '규칙동작'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.CONDITION_COMBINATION IS '규칙조건조합'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.SEQ_IDX_NUM IS '시퀀스고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_CONDITION_TYPE.BEFORE_CT_IDX_NUM IS '이전고유넘버'
;


    
CREATE TABLE TB_LCMS_SEQ_MAP_INFO (
	RLC_IDX_NUM NUMBER(9) DEFAULT 0,
	MAP_INFO_ID NUMBER(9) DEFAULT 0,
	TARGET_OBJ_ID VARCHAR(100),
	READ_STATUS VARCHAR(5),
	READ_MEASURE VARCHAR(5),
	WRITE_STATUS VARCHAR(5),
	WRITE_MEASURE VARCHAR(5),
	USERID VARCHAR(20),
	OBJECTIVE_IDX_NUM NUMBER(9) DEFAULT 0,
	UPDATE_DT DATE DEFAULT sysdate
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_MAP_INFO IS '학습목표맵정보'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.RLC_IDX_NUM IS '롤업조건번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.MAP_INFO_ID IS '맵정보아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.TARGET_OBJ_ID IS '전역학습목표매핑아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.READ_STATUS IS '전역학습목표만족상태검색'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.READ_MEASURE IS '전역학습목표평가검색'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.WRITE_STATUS IS '전역학습목표만족상태이동'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.WRITE_MEASURE IS '전역학습목표평가이동'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.OBJECTIVE_IDX_NUM IS '학습목표_일련번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_MAP_INFO.UPDATE_DT IS '갱신일자'
;


    
CREATE TABLE TB_LCMS_SEQ_OBJECTIVES (
	OBJECTIVE_IDX_NUM NUMBER(9) DEFAULT 0,
	OBJ_ID VARCHAR(100),
	SATISFIED_MEASURE VARCHAR(5),
	MINNORMAL_MEASURE VARCHAR(10),
	OBJ_TYPE VARCHAR(20),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	SEQ_IDX_NUM NUMBER(9) DEFAULT 0,
	BEFORE_OBJECTIVE_IDX_NUM NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_OBJECTIVES IS '과정학습목표'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.OBJECTIVE_IDX_NUM IS '학습목표_일련번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.OBJ_ID IS '학습목표아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.SATISFIED_MEASURE IS '만족평가'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.MINNORMAL_MEASURE IS '최소만족평가'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.OBJ_TYPE IS '객체타입'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.SEQ_IDX_NUM IS '시퀀스고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_OBJECTIVES.BEFORE_OBJECTIVE_IDX_NUM IS '이전목표고유번호'
;


    
CREATE TABLE TB_LCMS_SEQ_ROLLUP_CONDITION (
	RLC_IDX_NUM NUMBER(9) DEFAULT 0,
	ROLLUP_CONDITION_NUM NUMBER(9) DEFAULT 0,
	OPERATOR VARCHAR(20),
	CONDITION VARCHAR(25),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	RR_IDX_NUM NUMBER(9) DEFAULT 0
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_ROLLUP_CONDITION IS '롤업조건'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.RLC_IDX_NUM IS '롤업조건번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.ROLLUP_CONDITION_NUM IS '롤업조건아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.OPERATOR IS '연산자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.CONDITION IS '조건'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_CONDITION.RR_IDX_NUM IS '롤업고유번호'
;


    
CREATE TABLE TB_LCMS_SEQ_ROLLUP_RULE (
	RR_IDX_NUM NUMBER(9) DEFAULT 0,
	CHILD_ACTIVITY_SET VARCHAR(14),
	MINIMUM_COUNT NUMBER(9) DEFAULT 0,
	MINIMUM_PERCENT VARCHAR(14),
	ROLLUP_ACTION VARCHAR(12),
	CONDITION_COMBINATION VARCHAR(20),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate,
	SEQ_IDX_NUM NUMBER(9) DEFAULT 0,
	BEFORE_RR_IDX_NUM NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_ROLLUP_RULE IS '롤업규칙'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.RR_IDX_NUM IS '롤업고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.CHILD_ACTIVITY_SET IS '자식학습활동집합'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.MINIMUM_COUNT IS '최소자식수'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.MINIMUM_PERCENT IS '최소자식비율'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.ROLLUP_ACTION IS '롤업동작'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.CONDITION_COMBINATION IS '규칙조건조합'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.UPDATE_DT IS '갱신일자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.SEQ_IDX_NUM IS '시퀀스고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_ROLLUP_RULE.BEFORE_RR_IDX_NUM IS '이전롤업고유번호'
;


    
CREATE TABLE TB_LCMS_SEQ_RULE_CONDITION (
	RC_IDX_NUM NUMBER(9) DEFAULT 0,
	CT_IDX_NUM NUMBER(9) DEFAULT 0,
	RULE_CONDITION_ID NUMBER(9) DEFAULT 0,
	REFERENCE_OBJECTIVE VARCHAR(100),
	MEASURE_THRESHOLD VARCHAR(10),
	OPERATOR VARCHAR(20),
	CONDITION VARCHAR(25),
	USERID VARCHAR(20),
	UPDATE_DT DATE DEFAULT sysdate
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SEQ_RULE_CONDITION IS '규칙조건'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.RC_IDX_NUM IS '규칙조건번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.CT_IDX_NUM IS '규칙조건타입번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.RULE_CONDITION_ID IS '규칙조건집합아이디'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.REFERENCE_OBJECTIVE IS '참조학습목표'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.MEASURE_THRESHOLD IS '측정값임계치'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.OPERATOR IS '연산자'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.CONDITION IS '조건'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_SEQ_RULE_CONDITION.UPDATE_DT IS '갱신일자'
;


    
CREATE TABLE TB_LCMS_SERIALIZER (
	IDX NUMBER(9),
	COURSE_SEQ NUMBER(9),
	ORG_SEQ NUMBER(9) DEFAULT 0,
	SERIALIZER BLOB
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_SERIALIZER IS '직렬화정보'
;
COMMENT ON COLUMN TB_LCMS_SERIALIZER.IDX IS '직렬화고유번호'
;
COMMENT ON COLUMN TB_LCMS_SERIALIZER.COURSE_SEQ IS '과정순번'
;
COMMENT ON COLUMN TB_LCMS_SERIALIZER.ORG_SEQ IS '학습주제_일련번호'
;


    
CREATE TABLE TB_LCMS_TOC (
	TOC_IDX NUMBER(9),
	USERID VARCHAR(20),
	COURSE_MAP_SEQ NUMBER(11),
	IDX NUMBER(9),
	SERIALIZER BLOB,
	ORG_SEQ NUMBER(9)
)
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
COMMENT ON TABLE TB_LCMS_TOC IS '객체트리정보'
;
COMMENT ON COLUMN TB_LCMS_TOC.TOC_IDX IS 'TOC_IDX'
;
COMMENT ON COLUMN TB_LCMS_TOC.USERID IS '학습자고유번호'
;
COMMENT ON COLUMN TB_LCMS_TOC.COURSE_MAP_SEQ IS '맵핑시퀀스'
;
COMMENT ON COLUMN TB_LCMS_TOC.IDX IS '직렬화고유번호'
;
COMMENT ON COLUMN TB_LCMS_TOC.SERIALIZER IS '학습계체 직렬화'
;
COMMENT ON COLUMN TB_LCMS_TOC.ORG_SEQ IS '학습주제'
;













CREATE SEQUENCE SEQ_LCMS_METADATA_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 9999999999
    NOMINVALUE
    NOCYCLE
    NOCACHE
    NOORDER



  ;






CREATE INDEX IDX_LCMS_CMI_COMMENTFROMLMS_01 ON TB_LCMS_CMI_COMMENTFROMLMS (
	LEARNER_ID ASC,
	ITEM_ID ASC,
	COURSE_MAP_SEQ ASC,
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005514 ON TB_LCMS_CMI_COMMENTFROMLMS (
	COMMENTS_LMS_COMMENT_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;

CREATE INDEX IDX_LCMS_CMI_COMMENTLEARNER_01 ON TB_LCMS_CMI_COMMENTLEARNER (
	LEARNER_ID ASC,
	ITEM_ID ASC,
	COURSE_MAP_SEQ ASC,
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005515 ON TB_LCMS_CMI_COMMENTLEARNER (
	COMMENTS_LEARNER_CMT_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;

CREATE INDEX IDX_LCMS_CMI_IA_01 ON TB_LCMS_CMI_IA (
	COURSE_MAP_SEQ ASC,
	ORG_SEQ ASC,
	ITEM_ID ASC,
	LEARNER_ID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005516 ON TB_LCMS_CMI_IA (
	INTERACTIONS_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_CMI_OBJECTCOMMONINFO_01 ON TB_LCMS_CMI_OBJECTCOMMONINFO (
	USERID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005519 ON TB_LCMS_CMI_OBJECTCOMMONINFO (
	SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005520 ON TB_LCMS_CMI_OBJECTINFO (
	COURSE_MAP_SEQ ASC,
	ORG_SEQ ASC,
	ITEM_ID ASC,
	LEARNER_ID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    

CREATE INDEX IDX_LCMS_CMI_OBJECTIVES_01 ON TB_LCMS_CMI_OBJECTIVES (
	COURSE_MAP_SEQ ASC,
	ORG_SEQ ASC,
	ITEM_ID ASC,
	LEARNER_ID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005521 ON TB_LCMS_CMI_OBJECTIVES (
	OBJECTIVES_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    


CREATE INDEX IDX_LCMS_COURSE_MAP_01 ON TB_LCMS_COURSE_MAP (
	SUBJ ASC,
	YEAR ASC,
	SUBJSEQ ASC,
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005531 ON TB_LCMS_COURSE_MAP (
	COURSE_MAP_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_COURSE_ORG_01 ON TB_LCMS_COURSE_ORG (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX PK_COURSE_ORG ON TB_LCMS_COURSE_ORG (
	SUBJ ASC,
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_FILE_01 ON TB_LCMS_FILE (
	RSRC_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX TB_LCMS_FILE_PK ON TB_LCMS_FILE (
	LCMS_FILE_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX EDUUP_CON1763900000 ON TB_LCMS_GLOBALOBJ (
	OBJID ASC,
	USERID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE INDEX IDX_LCMS_GLOBALOBJ_01 ON TB_LCMS_GLOBALOBJ (
	USERID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_ITEM_ORG ON TB_LCMS_ITEM (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE INDEX IE1_LCMS_ITEM ON TB_LCMS_ITEM (
	HIGH_ITEM_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE INDEX IE2_LCMS_ITEM ON TB_LCMS_ITEM (
	ITEM_ID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005538 ON TB_LCMS_ITEM (
	ITEM_SEQ ASC,
	RSRC_SEQ ASC,
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_ITEM_RESOURCE_01 ON TB_LCMS_ITEM_RESOURCE (
	RSRC_SEQ ASC,
	GROUP_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005540 ON TB_LCMS_ITEM_RESOURCE (
	RSRC_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_LESSON_01 ON TB_LCMS_LESSON (
	SUBJ ASC,
	MODULE ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX TB_LCMS_LESSON_PK ON TB_LCMS_LESSON (
	SUBJ ASC,
	MODULE ASC,
	LESSON ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005541 ON TB_LCMS_MANISEQ (
	SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_MATERIAL_02 ON TB_LCMS_MATERIAL (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX LCMS_MATERIAL_PK ON TB_LCMS_MATERIAL (
	MAT_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_METADATA_01 ON TB_LCMS_METADATA (
	METADATA_SEQ ASC,
	TEMPLATE_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX PK_LCMS_METADATA01 ON TB_LCMS_METADATA (
	METADATA_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_METADATA_ELEMENT_01 ON TB_LCMS_METADATA_ELEMENT (
	ELEMENT_SEQ ASC,
	METADATA_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX PK_LCMS_METADATA_ELEMENT01 ON TB_LCMS_METADATA_ELEMENT (
	ELEMENT_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_METADATA_MAP ON TB_LCMS_METADATA_MAP (
	ELEMENT_PATH ASC,
	METATYPE ASC,
	OBJ_TYPE ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_LCMS_METADATA_TEMPLATE01 ON TB_LCMS_METADATA_TEMPLATE (
	TEMPLATE_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_LCMS_METADATA_VOCA01 ON TB_LCMS_METADATA_VOCA (
	VOCA_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_MODULE_01 ON TB_LCMS_MODULE (
	SUBJ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX TB_LCMS_MODULE_PK ON TB_LCMS_MODULE (
	SUBJ ASC,
	MODULE ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_ORGANIZATION_01 ON TB_LCMS_ORGANIZATION (
	ORG_SEQ ASC,
	GROUP_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX PK_ORGANIZATION ON TB_LCMS_ORGANIZATION (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_ORGANIZATION_LOG ON TB_LCMS_ORGANIZATION_LOG (
	LOG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX TB_LCMS_PROGRESS_PK ON TB_LCMS_PROGRESS (
	SUBJ ASC,
	YEAR ASC,
	SUBJSEQ ASC,
	MODULE ASC,
	LESSON ASC,
	USERID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    

CREATE UNIQUE INDEX SYS_C005545 ON TB_LCMS_REPOSITORY_CATEGORY (
	REP_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_RESOURCE_DEPENDENCY ON TB_LCMS_RESOURCE_DEPENDENCY (
	SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX PK_RESOURCE_FORMATION ON TB_LCMS_RESOURCE_FORMATION (
	SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005441 ON TB_LCMS_RTE_CONFIG (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_RTE_LOG_01 ON TB_LCMS_RTE_LOG (
	USERID ASC,
	COURSE_MAP_SEQ ASC,
	ITEM_ID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005442 ON TB_LCMS_RTE_LOG (
	LOG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX TB_LCMS_RTE_THEME_PK ON TB_LCMS_RTE_THEME (
	THEME_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_SCORM_SEQUENCE_01 ON TB_LCMS_SCORM_SEQUENCE (
	ITEM_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005454 ON TB_LCMS_SCORM_SEQUENCE (
	SEQ_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005619 ON TB_LCMS_SEQ_CONDITION_TYPE (
	CT_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005621 ON TB_LCMS_SEQ_MAP_INFO (
	RLC_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005623 ON TB_LCMS_SEQ_OBJECTIVES (
	OBJECTIVE_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005624 ON TB_LCMS_SEQ_ROLLUP_CONDITION (
	RLC_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005625 ON TB_LCMS_SEQ_ROLLUP_RULE (
	RR_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE UNIQUE INDEX SYS_C005456 ON TB_LCMS_SEQ_RULE_CONDITION (
	RC_IDX_NUM ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_SERIALIZER_01 ON TB_LCMS_SERIALIZER (
	ORG_SEQ ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005457 ON TB_LCMS_SERIALIZER (
	IDX ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    
CREATE INDEX IDX_LCMS_TOC_02 ON TB_LCMS_TOC (
	USERID ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;
CREATE UNIQUE INDEX SYS_C005426 ON TB_LCMS_TOC (
	TOC_IDX ASC
)
LOGGING
TABLESPACE NEWKNISE
PCTFREE 10
INITRANS 2
;    










